name: IronGate CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-go-demo:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/apps/go_server
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.0"

      - name: Build hello-api-go
        run: |
          go build -v server.go
          go run server.go
